### ISSUE TITLE
Make an export function for citations

### ISSUE THREAD

**Issue by gbif-portal** [gbif/literature-ws#12]
**Make an export function for citations**

In the same way that we have an export function for dataset searches or for download statistics (like this https://api.gbif.org/v1/occurrence/download/statistics/export?publishingCountry=CR&fromDate=2015-12&toDate=2019-11), I think publishers would really appreciate if they could download the citations in a CSV file.
This would facilitate their reporting.

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/ad0b48a1857af3e9f96197b0ff4c4c01:711d6b96db87d79afe2df5d51888705a2a6dcf2f10a812dd1e09fc64ce3bac3a3f606cbbde7fc7be0735a041d83aea927326c8da10c5fccbd8138d2af210b36ffca2f23298306e96cf9fbc4934eb778a7b1714a4211bece1877e4cf229f4c534b3444708ab2844f11dc1d8d8683303890d18f91b12cd80bdb2906408c5a31c454934adeffc8401844c3326e607adbe16) - [Send email](https://www.gbif.org/api/feedback/user/mailto/ad0b48a1857af3e9f96197b0ff4c4c01:711d6b96db87d79afe2df5d51888705a2a6dcf2f10a812dd1e09fc64ce3bac3a3f606cbbde7fc7be0735a041d83aea927326c8da10c5fccbd8138d2af210b36ffca2f23298306e96cf9fbc4934eb778a7b1714a4211bece1877e4cf229f4c534b3444708ab2844f11dc1d8d8683303890d18f91b12cd80bdb2906408c5a31c454934adeffc8401844c3326e607adbe16)
System: Safari 16.1.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/resource/search?contentType=literature&year=2022&publishingOrganizationKey=e8eada63-4a33-44aa-b2fd-4f71efb222a0
Window size: width 1479 - height 859
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-15T14:58:37.912Z',to:'2023-02-15T15:04:37.912Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-15T14:58:37.912Z',to:'2023-02-15T15:04:37.912Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by marcos-lg** [comment]
Just deployed it to UAT: https://api.gbif-uat.org/v1/literature/export

You can use the same query parameters as in the search. It works as other export endpoints that we have like the download statistics.

**Comment by dnoesgaard** [comment]
Wow, that was fast :)

I would like to see these fields in the export:

discovered
published
openAccess
peerReview
citationType
countriesOfCoverage
countriesOfResearcher

These are not necessary:
year
month
day

(gbif_download_key doesn't seem to be working correctly?)

**Comment by MattBlissett** [comment]
I'd also like to check the documentation is correct before releasing this, not only for the new function. I'll look tomorrow.

**Comment by MattBlissett** [comment]
Why are year, month and day not necessary?

**Comment by ManonGros** [comment]
I think year should be included at least, shouldn't it? (If the purpose is to report to funders, it might be helpful to have)

**Comment by dnoesgaard** [comment]
year, month and day are the same as published

**Comment by dnoesgaard** [comment]
For context, names of date fields are changed a bit on the import from Mendeley:

| Mendeley      | Lit API                                   |
|---------------|-------------------------------------------|
| year          | (unchanged)                               |
| month         | (unchanged)                               |
| day           | (unchanged)                               |
| created       | added                                     |
| accessed      | discovered                                |
|               | published (derived from year, month, day) |
| last_modified | modified                                  |

**Comment by marcos-lg** [comment]
> Question for everyone, should there be spaces around the pipes?
This is the current type of data:
Graciela D. Ávila-Quezada|José G. Torres-Martínez|Mamoudou Sétamou|Alfonso A. Gardea-Béjar|César A. Berzoza-Gaytán|Nuvia Orduño-Cruz
But it could be like:
Graciela D. Ávila-Quezada | José G. Torres-Martínez | Mamoudou Sétamou | Alfonso A. Gardea-Béjar | César A. Berzoza-Gaytán | Nuvia Orduño-Cruz

I think that if users will work with these exports by using scripts or other programmatic tools it's better not to add spaces so it's easier to split the values and work with them. Spaces would be good only for cases such as displaying them directly in a website since it looks nicer.

**Comment by marcos-lg** [comment]
Deployed to PROD

**Comment by MortenHofft** [comment]
dataset export use the form `https://api.gbif.org/v1/dataset/search/export?format=TSV&{query}`
Should we be consistent and use `https://api.gbif-uat.org/v1/literature/search/export?format=TSV&{usual query params here}`

I'm not sure what we do elsewhere? But it would make sense to align the urls I find

**Comment by marcos-lg** [comment]
In datasets there is the `dataset?{query}` that retrieves the data from postgres and the `dataset/search?{query}` that retrieves the data from ES. And the export is only for the ES data so that's why the `export` is under the search. in collections for example it's `/grscicoll/collection/export`

In the case of the literature there is only one source of data so I think it could be both. I found `literature/search/export` too verbose.

**Comment by MortenHofft** [comment]
Thanks Marcos - but literature is in fact under `/search` and ES like datasets. I do not have a strong opinion, but had expected it to be nested under `search`. That said I agree it is verbose.

**Comment by marcos-lg** [comment]
it should work now

**Comment by ManonGros** [comment]
Thanks Marcos! It looks like the limit is now 15,000. This is still not enough to download the whole GBIF literature. But maybe that's ok, it might be good to put a warning somewhere though.
